export const USER_INFORMATION_REQUEST =
  "userPageReducer/USER_INFORMATION_REQUEST";
export const USER_INFORMATION_SUCCESS =
  "userPageReducer/USER_INFORMATION_SUCCESS";
export const USER_INFORMATION_FAILED =
  "userPageReducer/USER_INFORMATION_FAILED";

export const USER_INFORMATION_UPDATE_REQUEST =
  "userPageReducer/USER_INFORMATION_UPDATE_REQUEST";
export const USER_INFORMATION_UPDATE_SUCCESS =
  "userPageReducer/USER_INFORMATION_UPDATE_SUCCESS";
export const USER_INFORMATION_UPDATE_FAILED =
  "userPageReducer/USER_INFORMATION_UPDATE_FAILED";
